; SCSyscalls.asm -- generated by SysWhispers4
; Method     : indirect
; Resolution : recycled
; Arch       : x64 / MASM (ml64.exe)
;
; Build: cl /nologo ... SCSyscalls.c SCSyscalls.asm
;        (ensure MASM64 is enabled in project settings)

OPTION DOTNAME

SC_XOR_KEY = 30C673B1h

.data
    EXTERN SC_SsnTable:DWORD
    EXTERN SC_SyscallAddrTable:QWORD

.code

; --- SC_NtWriteFile (indirect: jmp to syscall;ret in ntdll) ---
SC_NtWriteFile PROC
    mov r10, rcx                            ; syscall ABI: arg1 -> r10
    test r11d, 008h
    nop DWORD PTR [rax]
    nop WORD PTR [rax + rax]
    mov r11d, 0E9h
    nop WORD PTR [rax + rax]
    mov eax, DWORD PTR [SC_SsnTable + 0]  ; load encrypted SSN
    xor eax, SC_XOR_KEY                           ; decrypt
    jmp QWORD PTR [SC_SyscallAddrTable + 0]     ; -> ntdll gadget
SC_NtWriteFile ENDP


; --- SC_NtContinue (indirect: jmp to syscall;ret in ntdll) ---
SC_NtContinue PROC
    mov r10, rcx                            ; syscall ABI: arg1 -> r10
    lea rsp, [rsp + 00h]
    mov eax, DWORD PTR [SC_SsnTable + 4]  ; load encrypted SSN
    xor eax, SC_XOR_KEY                           ; decrypt
    jmp QWORD PTR [SC_SyscallAddrTable + 8]     ; -> ntdll gadget
SC_NtContinue ENDP


; --- SC_NtQueueApcThread (indirect: jmp to syscall;ret in ntdll) ---
SC_NtQueueApcThread PROC
    mov r10, rcx                            ; syscall ABI: arg1 -> r10
    test r11d, 0EEh
    lea rsp, [rsp + 00h]
    nop WORD PTR [rax + rax]
    mov eax, DWORD PTR [SC_SsnTable + 8]  ; load encrypted SSN
    xor eax, SC_XOR_KEY                           ; decrypt
    jmp QWORD PTR [SC_SyscallAddrTable + 16]     ; -> ntdll gadget
SC_NtQueueApcThread ENDP


; --- SC_NtQueryInformationProcess (indirect: jmp to syscall;ret in ntdll) ---
SC_NtQueryInformationProcess PROC
    mov r10, rcx                            ; syscall ABI: arg1 -> r10
    test r11d, 0BEh
    mov r11d, 04Fh
    lea rsp, [rsp + 00h]
    mov eax, DWORD PTR [SC_SsnTable + 12]  ; load encrypted SSN
    xor eax, SC_XOR_KEY                           ; decrypt
    jmp QWORD PTR [SC_SyscallAddrTable + 24]     ; -> ntdll gadget
SC_NtQueryInformationProcess ENDP


; --- SC_NtOpenProcessTokenEx (indirect: jmp to syscall;ret in ntdll) ---
SC_NtOpenProcessTokenEx PROC
    mov r10, rcx                            ; syscall ABI: arg1 -> r10
    push 0D6h
    pop r11
    lea r11, [r11]
    nop DWORD PTR [rax + 00h]
    lea r11, [r11]
    mov eax, DWORD PTR [SC_SsnTable + 16]  ; load encrypted SSN
    xor eax, SC_XOR_KEY                           ; decrypt
    jmp QWORD PTR [SC_SyscallAddrTable + 32]     ; -> ntdll gadget
SC_NtOpenProcessTokenEx ENDP


; --- SC_NtTerminateProcess (indirect: jmp to syscall;ret in ntdll) ---
SC_NtTerminateProcess PROC
    mov r10, rcx                            ; syscall ABI: arg1 -> r10
    xchg r11, r11
    push 085h
    pop r11
    mov eax, DWORD PTR [SC_SsnTable + 20]  ; load encrypted SSN
    xor eax, SC_XOR_KEY                           ; decrypt
    jmp QWORD PTR [SC_SyscallAddrTable + 40]     ; -> ntdll gadget
SC_NtTerminateProcess ENDP


; --- SC_NtUnmapViewOfSection (indirect: jmp to syscall;ret in ntdll) ---
SC_NtUnmapViewOfSection PROC
    mov r10, rcx                            ; syscall ABI: arg1 -> r10
    lea rsp, [rsp + 00h]
    nop
    mov eax, DWORD PTR [SC_SsnTable + 24]  ; load encrypted SSN
    xor eax, SC_XOR_KEY                           ; decrypt
    jmp QWORD PTR [SC_SyscallAddrTable + 48]     ; -> ntdll gadget
SC_NtUnmapViewOfSection ENDP


; --- SC_NtOpenThread (indirect: jmp to syscall;ret in ntdll) ---
SC_NtOpenThread PROC
    mov r10, rcx                            ; syscall ABI: arg1 -> r10
    xor r11d, r11d
    or r11d, r11d
    nop DWORD PTR [rax]
    push 086h
    pop r11
    mov eax, DWORD PTR [SC_SsnTable + 28]  ; load encrypted SSN
    xor eax, SC_XOR_KEY                           ; decrypt
    jmp QWORD PTR [SC_SyscallAddrTable + 56]     ; -> ntdll gadget
SC_NtOpenThread ENDP


; --- SC_NtCreateProcess (indirect: jmp to syscall;ret in ntdll) ---
SC_NtCreateProcess PROC
    mov r10, rcx                            ; syscall ABI: arg1 -> r10
    push 0CAh
    pop r11
    lea rsp, [rsp + 00h]
    mov eax, DWORD PTR [SC_SsnTable + 32]  ; load encrypted SSN
    xor eax, SC_XOR_KEY                           ; decrypt
    jmp QWORD PTR [SC_SyscallAddrTable + 64]     ; -> ntdll gadget
SC_NtCreateProcess ENDP


; --- SC_NtImpersonateThread (indirect: jmp to syscall;ret in ntdll) ---
SC_NtImpersonateThread PROC
    mov r10, rcx                            ; syscall ABI: arg1 -> r10
    xchg ax, ax
    lea rsp, [rsp + 00h]
    lea rsp, [rsp + 00h]
    mov eax, DWORD PTR [SC_SsnTable + 36]  ; load encrypted SSN
    xor eax, SC_XOR_KEY                           ; decrypt
    jmp QWORD PTR [SC_SyscallAddrTable + 72]     ; -> ntdll gadget
SC_NtImpersonateThread ENDP


; --- SC_NtAdjustPrivilegesToken (indirect: jmp to syscall;ret in ntdll) ---
SC_NtAdjustPrivilegesToken PROC
    mov r10, rcx                            ; syscall ABI: arg1 -> r10
    test r11d, 05Bh
    fnop
    mov eax, DWORD PTR [SC_SsnTable + 40]  ; load encrypted SSN
    xor eax, SC_XOR_KEY                           ; decrypt
    jmp QWORD PTR [SC_SyscallAddrTable + 80]     ; -> ntdll gadget
SC_NtAdjustPrivilegesToken ENDP


; --- SC_NtWaitForSingleObject (indirect: jmp to syscall;ret in ntdll) ---
SC_NtWaitForSingleObject PROC
    mov r10, rcx                            ; syscall ABI: arg1 -> r10
    cmp r11d, 066h
    mov eax, DWORD PTR [SC_SsnTable + 44]  ; load encrypted SSN
    xor eax, SC_XOR_KEY                           ; decrypt
    jmp QWORD PTR [SC_SyscallAddrTable + 88]     ; -> ntdll gadget
SC_NtWaitForSingleObject ENDP


; --- SC_NtAlertResumeThread (indirect: jmp to syscall;ret in ntdll) ---
SC_NtAlertResumeThread PROC
    mov r10, rcx                            ; syscall ABI: arg1 -> r10
    xchg r11, r11
    test r11d, 04Dh
    xchg r11, r11
    push 0C7h
    pop r11
    mov eax, DWORD PTR [SC_SsnTable + 48]  ; load encrypted SSN
    xor eax, SC_XOR_KEY                           ; decrypt
    jmp QWORD PTR [SC_SyscallAddrTable + 96]     ; -> ntdll gadget
SC_NtAlertResumeThread ENDP


; --- SC_NtOpenFile (indirect: jmp to syscall;ret in ntdll) ---
SC_NtOpenFile PROC
    mov r10, rcx                            ; syscall ABI: arg1 -> r10
    cmp r11d, 0E2h
    mov eax, DWORD PTR [SC_SsnTable + 52]  ; load encrypted SSN
    xor eax, SC_XOR_KEY                           ; decrypt
    jmp QWORD PTR [SC_SyscallAddrTable + 104]     ; -> ntdll gadget
SC_NtOpenFile ENDP


; --- SC_NtWaitForMultipleObjects (indirect: jmp to syscall;ret in ntdll) ---
SC_NtWaitForMultipleObjects PROC
    mov r10, rcx                            ; syscall ABI: arg1 -> r10
    push 054h
    pop r11
    test r11d, 026h
    fnop
    lea r11, [r11]
    nop
    mov eax, DWORD PTR [SC_SsnTable + 56]  ; load encrypted SSN
    xor eax, SC_XOR_KEY                           ; decrypt
    jmp QWORD PTR [SC_SyscallAddrTable + 112]     ; -> ntdll gadget
SC_NtWaitForMultipleObjects ENDP


; --- SC_NtWriteVirtualMemory (indirect: jmp to syscall;ret in ntdll) ---
SC_NtWriteVirtualMemory PROC
    mov r10, rcx                            ; syscall ABI: arg1 -> r10
    fnop
    push 032h
    pop r11
    mov eax, DWORD PTR [SC_SsnTable + 60]  ; load encrypted SSN
    xor eax, SC_XOR_KEY                           ; decrypt
    jmp QWORD PTR [SC_SyscallAddrTable + 120]     ; -> ntdll gadget
SC_NtWriteVirtualMemory ENDP


; --- SC_NtTestAlert (indirect: jmp to syscall;ret in ntdll) ---
SC_NtTestAlert PROC
    mov r10, rcx                            ; syscall ABI: arg1 -> r10
    nop DWORD PTR [rax]
    lea r11, [r11]
    mov r11d, 0D6h
    xchg ax, ax
    push 0A8h
    pop r11
    mov eax, DWORD PTR [SC_SsnTable + 64]  ; load encrypted SSN
    xor eax, SC_XOR_KEY                           ; decrypt
    jmp QWORD PTR [SC_SyscallAddrTable + 128]     ; -> ntdll gadget
SC_NtTestAlert ENDP


; --- SC_NtRollbackTransaction (indirect: jmp to syscall;ret in ntdll) ---
SC_NtRollbackTransaction PROC
    mov r10, rcx                            ; syscall ABI: arg1 -> r10
    push 0D3h
    pop r11
    push 0D3h
    pop r11
    mov r11d, 0DFh
    mov eax, DWORD PTR [SC_SsnTable + 68]  ; load encrypted SSN
    xor eax, SC_XOR_KEY                           ; decrypt
    jmp QWORD PTR [SC_SyscallAddrTable + 136]     ; -> ntdll gadget
SC_NtRollbackTransaction ENDP


; --- SC_NtSetTimer (indirect: jmp to syscall;ret in ntdll) ---
SC_NtSetTimer PROC
    mov r10, rcx                            ; syscall ABI: arg1 -> r10
    nop DWORD PTR [rax + 00h]
    nop
    mov eax, DWORD PTR [SC_SsnTable + 72]  ; load encrypted SSN
    xor eax, SC_XOR_KEY                           ; decrypt
    jmp QWORD PTR [SC_SyscallAddrTable + 144]     ; -> ntdll gadget
SC_NtSetTimer ENDP


; --- SC_NtClose (indirect: jmp to syscall;ret in ntdll) ---
SC_NtClose PROC
    mov r10, rcx                            ; syscall ABI: arg1 -> r10
    lea r11, [r11]
    push 04Eh
    pop r11
    mov eax, DWORD PTR [SC_SsnTable + 76]  ; load encrypted SSN
    xor eax, SC_XOR_KEY                           ; decrypt
    jmp QWORD PTR [SC_SyscallAddrTable + 152]     ; -> ntdll gadget
SC_NtClose ENDP


; --- SC_NtAlertThread (indirect: jmp to syscall;ret in ntdll) ---
SC_NtAlertThread PROC
    mov r10, rcx                            ; syscall ABI: arg1 -> r10
    lea rsp, [rsp + 00h]
    mov eax, DWORD PTR [SC_SsnTable + 80]  ; load encrypted SSN
    xor eax, SC_XOR_KEY                           ; decrypt
    jmp QWORD PTR [SC_SyscallAddrTable + 160]     ; -> ntdll gadget
SC_NtAlertThread ENDP


; --- SC_NtCreateUserProcess (indirect: jmp to syscall;ret in ntdll) ---
SC_NtCreateUserProcess PROC
    mov r10, rcx                            ; syscall ABI: arg1 -> r10
    test r11d, 020h
    mov eax, DWORD PTR [SC_SsnTable + 84]  ; load encrypted SSN
    xor eax, SC_XOR_KEY                           ; decrypt
    jmp QWORD PTR [SC_SyscallAddrTable + 168]     ; -> ntdll gadget
SC_NtCreateUserProcess ENDP


; --- SC_NtUnloadDriver (indirect: jmp to syscall;ret in ntdll) ---
SC_NtUnloadDriver PROC
    mov r10, rcx                            ; syscall ABI: arg1 -> r10
    xchg r11, r11
    xchg ax, ax
    xchg r11, r11
    nop DWORD PTR [rax + 00h]
    lea r11, [r11]
    mov eax, DWORD PTR [SC_SsnTable + 88]  ; load encrypted SSN
    xor eax, SC_XOR_KEY                           ; decrypt
    jmp QWORD PTR [SC_SyscallAddrTable + 176]     ; -> ntdll gadget
SC_NtUnloadDriver ENDP


; --- SC_NtSetEvent (indirect: jmp to syscall;ret in ntdll) ---
SC_NtSetEvent PROC
    mov r10, rcx                            ; syscall ABI: arg1 -> r10
    xor r11d, r11d
    or r11d, r11d
    nop DWORD PTR [rax]
    mov eax, DWORD PTR [SC_SsnTable + 92]  ; load encrypted SSN
    xor eax, SC_XOR_KEY                           ; decrypt
    jmp QWORD PTR [SC_SyscallAddrTable + 184]     ; -> ntdll gadget
SC_NtSetEvent ENDP


; --- SC_NtMapViewOfSection (indirect: jmp to syscall;ret in ntdll) ---
SC_NtMapViewOfSection PROC
    mov r10, rcx                            ; syscall ABI: arg1 -> r10
    nop
    mov eax, DWORD PTR [SC_SsnTable + 96]  ; load encrypted SSN
    xor eax, SC_XOR_KEY                           ; decrypt
    jmp QWORD PTR [SC_SyscallAddrTable + 192]     ; -> ntdll gadget
SC_NtMapViewOfSection ENDP


; --- SC_NtDelayExecution (indirect: jmp to syscall;ret in ntdll) ---
SC_NtDelayExecution PROC
    mov r10, rcx                            ; syscall ABI: arg1 -> r10
    xor r11d, r11d
    or r11d, r11d
    test r11d, 0E0h
    mov eax, DWORD PTR [SC_SsnTable + 100]  ; load encrypted SSN
    xor eax, SC_XOR_KEY                           ; decrypt
    jmp QWORD PTR [SC_SyscallAddrTable + 200]     ; -> ntdll gadget
SC_NtDelayExecution ENDP


; --- SC_NtSuspendThread (indirect: jmp to syscall;ret in ntdll) ---
SC_NtSuspendThread PROC
    mov r10, rcx                            ; syscall ABI: arg1 -> r10
    nop DWORD PTR [rax + 00h]
    lea rsp, [rsp + 00h]
    push 051h
    pop r11
    xchg r11, r11
    mov eax, DWORD PTR [SC_SsnTable + 104]  ; load encrypted SSN
    xor eax, SC_XOR_KEY                           ; decrypt
    jmp QWORD PTR [SC_SyscallAddrTable + 208]     ; -> ntdll gadget
SC_NtSuspendThread ENDP


; --- SC_NtOpenProcessToken (indirect: jmp to syscall;ret in ntdll) ---
SC_NtOpenProcessToken PROC
    mov r10, rcx                            ; syscall ABI: arg1 -> r10
    xor r11d, r11d
    or r11d, r11d
    xor r11d, r11d
    or r11d, r11d
    mov eax, DWORD PTR [SC_SsnTable + 108]  ; load encrypted SSN
    xor eax, SC_XOR_KEY                           ; decrypt
    jmp QWORD PTR [SC_SyscallAddrTable + 216]     ; -> ntdll gadget
SC_NtOpenProcessToken ENDP


; --- SC_NtFlushInstructionCache (indirect: jmp to syscall;ret in ntdll) ---
SC_NtFlushInstructionCache PROC
    mov r10, rcx                            ; syscall ABI: arg1 -> r10
    xor r11d, r11d
    or r11d, r11d
    nop DWORD PTR [rax]
    mov eax, DWORD PTR [SC_SsnTable + 112]  ; load encrypted SSN
    xor eax, SC_XOR_KEY                           ; decrypt
    jmp QWORD PTR [SC_SyscallAddrTable + 224]     ; -> ntdll gadget
SC_NtFlushInstructionCache ENDP


; --- SC_NtCreateProcessEx (indirect: jmp to syscall;ret in ntdll) ---
SC_NtCreateProcessEx PROC
    mov r10, rcx                            ; syscall ABI: arg1 -> r10
    nop WORD PTR [rax + rax]
    mov r11d, 0DDh
    nop WORD PTR [rax + rax]
    mov eax, DWORD PTR [SC_SsnTable + 116]  ; load encrypted SSN
    xor eax, SC_XOR_KEY                           ; decrypt
    jmp QWORD PTR [SC_SyscallAddrTable + 232]     ; -> ntdll gadget
SC_NtCreateProcessEx ENDP


; --- SC_NtDeviceIoControlFile (indirect: jmp to syscall;ret in ntdll) ---
SC_NtDeviceIoControlFile PROC
    mov r10, rcx                            ; syscall ABI: arg1 -> r10
    test r11d, 05Dh
    xor r11d, r11d
    or r11d, r11d
    mov eax, DWORD PTR [SC_SsnTable + 120]  ; load encrypted SSN
    xor eax, SC_XOR_KEY                           ; decrypt
    jmp QWORD PTR [SC_SyscallAddrTable + 240]     ; -> ntdll gadget
SC_NtDeviceIoControlFile ENDP


; --- SC_NtSetInformationVirtualMemory (indirect: jmp to syscall;ret in ntdll) ---
SC_NtSetInformationVirtualMemory PROC
    mov r10, rcx                            ; syscall ABI: arg1 -> r10
    xchg r11, r11
    nop WORD PTR [rax + rax]
    mov eax, DWORD PTR [SC_SsnTable + 124]  ; load encrypted SSN
    xor eax, SC_XOR_KEY                           ; decrypt
    jmp QWORD PTR [SC_SyscallAddrTable + 248]     ; -> ntdll gadget
SC_NtSetInformationVirtualMemory ENDP


; --- SC_NtProtectVirtualMemory (indirect: jmp to syscall;ret in ntdll) ---
SC_NtProtectVirtualMemory PROC
    mov r10, rcx                            ; syscall ABI: arg1 -> r10
    nop WORD PTR [rax + rax]
    push 03Ah
    pop r11
    lea rsp, [rsp + 00h]
    xchg r11, r11
    mov r11d, 0D4h
    mov eax, DWORD PTR [SC_SsnTable + 128]  ; load encrypted SSN
    xor eax, SC_XOR_KEY                           ; decrypt
    jmp QWORD PTR [SC_SyscallAddrTable + 256]     ; -> ntdll gadget
SC_NtProtectVirtualMemory ENDP


; --- SC_NtQueryInformationThread (indirect: jmp to syscall;ret in ntdll) ---
SC_NtQueryInformationThread PROC
    mov r10, rcx                            ; syscall ABI: arg1 -> r10
    lea rsp, [rsp + 00h]
    mov eax, DWORD PTR [SC_SsnTable + 132]  ; load encrypted SSN
    xor eax, SC_XOR_KEY                           ; decrypt
    jmp QWORD PTR [SC_SyscallAddrTable + 264]     ; -> ntdll gadget
SC_NtQueryInformationThread ENDP


; --- SC_NtGetContextThread (indirect: jmp to syscall;ret in ntdll) ---
SC_NtGetContextThread PROC
    mov r10, rcx                            ; syscall ABI: arg1 -> r10
    test r11d, 008h
    lea r11, [r11]
    mov eax, DWORD PTR [SC_SsnTable + 136]  ; load encrypted SSN
    xor eax, SC_XOR_KEY                           ; decrypt
    jmp QWORD PTR [SC_SyscallAddrTable + 272]     ; -> ntdll gadget
SC_NtGetContextThread ENDP


; --- SC_NtOpenProcess (indirect: jmp to syscall;ret in ntdll) ---
SC_NtOpenProcess PROC
    mov r10, rcx                            ; syscall ABI: arg1 -> r10
    lea rsp, [rsp + 00h]
    mov eax, DWORD PTR [SC_SsnTable + 140]  ; load encrypted SSN
    xor eax, SC_XOR_KEY                           ; decrypt
    jmp QWORD PTR [SC_SyscallAddrTable + 280]     ; -> ntdll gadget
SC_NtOpenProcess ENDP


; --- SC_NtSetInformationThread (indirect: jmp to syscall;ret in ntdll) ---
SC_NtSetInformationThread PROC
    mov r10, rcx                            ; syscall ABI: arg1 -> r10
    push 0ABh
    pop r11
    test r11d, 065h
    push 0ABh
    pop r11
    test r11d, 065h
    lea r11, [r11]
    mov eax, DWORD PTR [SC_SsnTable + 144]  ; load encrypted SSN
    xor eax, SC_XOR_KEY                           ; decrypt
    jmp QWORD PTR [SC_SyscallAddrTable + 288]     ; -> ntdll gadget
SC_NtSetInformationThread ENDP


; --- SC_NtQueryInformationToken (indirect: jmp to syscall;ret in ntdll) ---
SC_NtQueryInformationToken PROC
    mov r10, rcx                            ; syscall ABI: arg1 -> r10
    lea rsp, [rsp + 00h]
    cmp r11d, 0EEh
    lea r11, [r11]
    mov eax, DWORD PTR [SC_SsnTable + 148]  ; load encrypted SSN
    xor eax, SC_XOR_KEY                           ; decrypt
    jmp QWORD PTR [SC_SyscallAddrTable + 296]     ; -> ntdll gadget
SC_NtQueryInformationToken ENDP


; --- SC_NtQueueApcThreadEx (indirect: jmp to syscall;ret in ntdll) ---
SC_NtQueueApcThreadEx PROC
    mov r10, rcx                            ; syscall ABI: arg1 -> r10
    mov r11d, 0A3h
    fnop
    nop
    mov r11d, 0A3h
    mov eax, DWORD PTR [SC_SsnTable + 152]  ; load encrypted SSN
    xor eax, SC_XOR_KEY                           ; decrypt
    jmp QWORD PTR [SC_SyscallAddrTable + 304]     ; -> ntdll gadget
SC_NtQueueApcThreadEx ENDP


; --- SC_NtAllocateVirtualMemoryEx (indirect: jmp to syscall;ret in ntdll) ---
SC_NtAllocateVirtualMemoryEx PROC
    mov r10, rcx                            ; syscall ABI: arg1 -> r10
    nop
    cmp r11d, 065h
    fnop
    mov eax, DWORD PTR [SC_SsnTable + 156]  ; load encrypted SSN
    xor eax, SC_XOR_KEY                           ; decrypt
    jmp QWORD PTR [SC_SyscallAddrTable + 312]     ; -> ntdll gadget
SC_NtAllocateVirtualMemoryEx ENDP


; --- SC_NtDuplicateToken (indirect: jmp to syscall;ret in ntdll) ---
SC_NtDuplicateToken PROC
    mov r10, rcx                            ; syscall ABI: arg1 -> r10
    xchg ax, ax
    lea rsp, [rsp + 00h]
    mov eax, DWORD PTR [SC_SsnTable + 160]  ; load encrypted SSN
    xor eax, SC_XOR_KEY                           ; decrypt
    jmp QWORD PTR [SC_SyscallAddrTable + 320]     ; -> ntdll gadget
SC_NtDuplicateToken ENDP


; --- SC_NtDuplicateObject (indirect: jmp to syscall;ret in ntdll) ---
SC_NtDuplicateObject PROC
    mov r10, rcx                            ; syscall ABI: arg1 -> r10
    nop DWORD PTR [rax]
    push 04Fh
    pop r11
    nop DWORD PTR [rax + 00h]
    nop DWORD PTR [rax]
    mov eax, DWORD PTR [SC_SsnTable + 164]  ; load encrypted SSN
    xor eax, SC_XOR_KEY                           ; decrypt
    jmp QWORD PTR [SC_SyscallAddrTable + 328]     ; -> ntdll gadget
SC_NtDuplicateObject ENDP


; --- SC_NtOpenThreadToken (indirect: jmp to syscall;ret in ntdll) ---
SC_NtOpenThreadToken PROC
    mov r10, rcx                            ; syscall ABI: arg1 -> r10
    test r11d, 0F6h
    nop DWORD PTR [rax + 00h]
    xchg ax, ax
    test r11d, 0F6h
    mov eax, DWORD PTR [SC_SsnTable + 168]  ; load encrypted SSN
    xor eax, SC_XOR_KEY                           ; decrypt
    jmp QWORD PTR [SC_SyscallAddrTable + 336]     ; -> ntdll gadget
SC_NtOpenThreadToken ENDP


; --- SC_NtQueryVirtualMemory (indirect: jmp to syscall;ret in ntdll) ---
SC_NtQueryVirtualMemory PROC
    mov r10, rcx                            ; syscall ABI: arg1 -> r10
    cmp r11d, 043h
    cmp r11d, 043h
    mov eax, DWORD PTR [SC_SsnTable + 172]  ; load encrypted SSN
    xor eax, SC_XOR_KEY                           ; decrypt
    jmp QWORD PTR [SC_SyscallAddrTable + 344]     ; -> ntdll gadget
SC_NtQueryVirtualMemory ENDP


; --- SC_NtCreateFile (indirect: jmp to syscall;ret in ntdll) ---
SC_NtCreateFile PROC
    mov r10, rcx                            ; syscall ABI: arg1 -> r10
    fnop
    mov eax, DWORD PTR [SC_SsnTable + 176]  ; load encrypted SSN
    xor eax, SC_XOR_KEY                           ; decrypt
    jmp QWORD PTR [SC_SyscallAddrTable + 352]     ; -> ntdll gadget
SC_NtCreateFile ENDP


; --- SC_NtCommitTransaction (indirect: jmp to syscall;ret in ntdll) ---
SC_NtCommitTransaction PROC
    mov r10, rcx                            ; syscall ABI: arg1 -> r10
    push 038h
    pop r11
    test r11d, 058h
    nop WORD PTR [rax + rax]
    lea r11, [r11]
    xchg r11, r11
    mov eax, DWORD PTR [SC_SsnTable + 180]  ; load encrypted SSN
    xor eax, SC_XOR_KEY                           ; decrypt
    jmp QWORD PTR [SC_SyscallAddrTable + 360]     ; -> ntdll gadget
SC_NtCommitTransaction ENDP


; --- SC_NtCreateSection (indirect: jmp to syscall;ret in ntdll) ---
SC_NtCreateSection PROC
    mov r10, rcx                            ; syscall ABI: arg1 -> r10
    nop WORD PTR [rax + rax]
    nop
    mov eax, DWORD PTR [SC_SsnTable + 184]  ; load encrypted SSN
    xor eax, SC_XOR_KEY                           ; decrypt
    jmp QWORD PTR [SC_SyscallAddrTable + 368]     ; -> ntdll gadget
SC_NtCreateSection ENDP


; --- SC_NtAllocateVirtualMemory (indirect: jmp to syscall;ret in ntdll) ---
SC_NtAllocateVirtualMemory PROC
    mov r10, rcx                            ; syscall ABI: arg1 -> r10
    nop
    lea r11, [r11]
    fnop
    fnop
    xchg r11, r11
    mov eax, DWORD PTR [SC_SsnTable + 188]  ; load encrypted SSN
    xor eax, SC_XOR_KEY                           ; decrypt
    jmp QWORD PTR [SC_SyscallAddrTable + 376]     ; -> ntdll gadget
SC_NtAllocateVirtualMemory ENDP


; --- SC_NtCreateTimer (indirect: jmp to syscall;ret in ntdll) ---
SC_NtCreateTimer PROC
    mov r10, rcx                            ; syscall ABI: arg1 -> r10
    test r11d, 038h
    lea rsp, [rsp + 00h]
    nop WORD PTR [rax + rax]
    nop DWORD PTR [rax]
    mov eax, DWORD PTR [SC_SsnTable + 192]  ; load encrypted SSN
    xor eax, SC_XOR_KEY                           ; decrypt
    jmp QWORD PTR [SC_SyscallAddrTable + 384]     ; -> ntdll gadget
SC_NtCreateTimer ENDP


; --- SC_NtQuerySystemInformation (indirect: jmp to syscall;ret in ntdll) ---
SC_NtQuerySystemInformation PROC
    mov r10, rcx                            ; syscall ABI: arg1 -> r10
    nop
    xchg r11, r11
    mov r11d, 0CBh
    mov eax, DWORD PTR [SC_SsnTable + 196]  ; load encrypted SSN
    xor eax, SC_XOR_KEY                           ; decrypt
    jmp QWORD PTR [SC_SyscallAddrTable + 392]     ; -> ntdll gadget
SC_NtQuerySystemInformation ENDP


; --- SC_NtDeleteFile (indirect: jmp to syscall;ret in ntdll) ---
SC_NtDeleteFile PROC
    mov r10, rcx                            ; syscall ABI: arg1 -> r10
    nop
    nop WORD PTR [rax + rax]
    xchg ax, ax
    mov eax, DWORD PTR [SC_SsnTable + 200]  ; load encrypted SSN
    xor eax, SC_XOR_KEY                           ; decrypt
    jmp QWORD PTR [SC_SyscallAddrTable + 400]     ; -> ntdll gadget
SC_NtDeleteFile ENDP


; --- SC_NtCreateEvent (indirect: jmp to syscall;ret in ntdll) ---
SC_NtCreateEvent PROC
    mov r10, rcx                            ; syscall ABI: arg1 -> r10
    xchg r11, r11
    mov eax, DWORD PTR [SC_SsnTable + 204]  ; load encrypted SSN
    xor eax, SC_XOR_KEY                           ; decrypt
    jmp QWORD PTR [SC_SyscallAddrTable + 408]     ; -> ntdll gadget
SC_NtCreateEvent ENDP


; --- SC_NtQueryObject (indirect: jmp to syscall;ret in ntdll) ---
SC_NtQueryObject PROC
    mov r10, rcx                            ; syscall ABI: arg1 -> r10
    nop
    lea rsp, [rsp + 00h]
    nop
    mov eax, DWORD PTR [SC_SsnTable + 208]  ; load encrypted SSN
    xor eax, SC_XOR_KEY                           ; decrypt
    jmp QWORD PTR [SC_SyscallAddrTable + 416]     ; -> ntdll gadget
SC_NtQueryObject ENDP


; --- SC_NtCreateTransaction (indirect: jmp to syscall;ret in ntdll) ---
SC_NtCreateTransaction PROC
    mov r10, rcx                            ; syscall ABI: arg1 -> r10
    lea r11, [r11]
    lea r11, [r11]
    xchg r11, r11
    push 0EFh
    pop r11
    nop
    mov eax, DWORD PTR [SC_SsnTable + 212]  ; load encrypted SSN
    xor eax, SC_XOR_KEY                           ; decrypt
    jmp QWORD PTR [SC_SyscallAddrTable + 424]     ; -> ntdll gadget
SC_NtCreateTransaction ENDP


; --- SC_NtFreeVirtualMemory (indirect: jmp to syscall;ret in ntdll) ---
SC_NtFreeVirtualMemory PROC
    mov r10, rcx                            ; syscall ABI: arg1 -> r10
    cmp r11d, 010h
    mov eax, DWORD PTR [SC_SsnTable + 216]  ; load encrypted SSN
    xor eax, SC_XOR_KEY                           ; decrypt
    jmp QWORD PTR [SC_SyscallAddrTable + 432]     ; -> ntdll gadget
SC_NtFreeVirtualMemory ENDP


; --- SC_NtSignalAndWaitForSingleObject (indirect: jmp to syscall;ret in ntdll) ---
SC_NtSignalAndWaitForSingleObject PROC
    mov r10, rcx                            ; syscall ABI: arg1 -> r10
    xchg ax, ax
    nop WORD PTR [rax + rax]
    nop
    mov eax, DWORD PTR [SC_SsnTable + 220]  ; load encrypted SSN
    xor eax, SC_XOR_KEY                           ; decrypt
    jmp QWORD PTR [SC_SyscallAddrTable + 440]     ; -> ntdll gadget
SC_NtSignalAndWaitForSingleObject ENDP


; --- SC_NtReadFile (indirect: jmp to syscall;ret in ntdll) ---
SC_NtReadFile PROC
    mov r10, rcx                            ; syscall ABI: arg1 -> r10
    nop DWORD PTR [rax + 00h]
    xchg ax, ax
    xor r11d, r11d
    or r11d, r11d
    nop
    mov eax, DWORD PTR [SC_SsnTable + 224]  ; load encrypted SSN
    xor eax, SC_XOR_KEY                           ; decrypt
    jmp QWORD PTR [SC_SyscallAddrTable + 448]     ; -> ntdll gadget
SC_NtReadFile ENDP


; --- SC_NtLoadDriver (indirect: jmp to syscall;ret in ntdll) ---
SC_NtLoadDriver PROC
    mov r10, rcx                            ; syscall ABI: arg1 -> r10
    test r11d, 067h
    xchg ax, ax
    xchg ax, ax
    lea rsp, [rsp + 00h]
    mov eax, DWORD PTR [SC_SsnTable + 228]  ; load encrypted SSN
    xor eax, SC_XOR_KEY                           ; decrypt
    jmp QWORD PTR [SC_SyscallAddrTable + 456]     ; -> ntdll gadget
SC_NtLoadDriver ENDP


; --- SC_NtSetContextThread (indirect: jmp to syscall;ret in ntdll) ---
SC_NtSetContextThread PROC
    mov r10, rcx                            ; syscall ABI: arg1 -> r10
    xchg ax, ax
    mov r11d, 0EAh
    xchg r11, r11
    nop DWORD PTR [rax + 00h]
    mov eax, DWORD PTR [SC_SsnTable + 232]  ; load encrypted SSN
    xor eax, SC_XOR_KEY                           ; decrypt
    jmp QWORD PTR [SC_SyscallAddrTable + 464]     ; -> ntdll gadget
SC_NtSetContextThread ENDP


; --- SC_NtCreateThreadEx (indirect: jmp to syscall;ret in ntdll) ---
SC_NtCreateThreadEx PROC
    mov r10, rcx                            ; syscall ABI: arg1 -> r10
    lea rsp, [rsp + 00h]
    nop
    test r11d, 015h
    xchg r11, r11
    mov eax, DWORD PTR [SC_SsnTable + 236]  ; load encrypted SSN
    xor eax, SC_XOR_KEY                           ; decrypt
    jmp QWORD PTR [SC_SyscallAddrTable + 472]     ; -> ntdll gadget
SC_NtCreateThreadEx ENDP


; --- SC_NtSuspendProcess (indirect: jmp to syscall;ret in ntdll) ---
SC_NtSuspendProcess PROC
    mov r10, rcx                            ; syscall ABI: arg1 -> r10
    push 0D5h
    pop r11
    xchg r11, r11
    xchg r11, r11
    test r11d, 075h
    push 0D5h
    pop r11
    mov eax, DWORD PTR [SC_SsnTable + 240]  ; load encrypted SSN
    xor eax, SC_XOR_KEY                           ; decrypt
    jmp QWORD PTR [SC_SyscallAddrTable + 480]     ; -> ntdll gadget
SC_NtSuspendProcess ENDP


; --- SC_NtOpenSection (indirect: jmp to syscall;ret in ntdll) ---
SC_NtOpenSection PROC
    mov r10, rcx                            ; syscall ABI: arg1 -> r10
    test r11d, 024h
    nop DWORD PTR [rax]
    mov eax, DWORD PTR [SC_SsnTable + 244]  ; load encrypted SSN
    xor eax, SC_XOR_KEY                           ; decrypt
    jmp QWORD PTR [SC_SyscallAddrTable + 488]     ; -> ntdll gadget
SC_NtOpenSection ENDP


; --- SC_NtReadVirtualMemory (indirect: jmp to syscall;ret in ntdll) ---
SC_NtReadVirtualMemory PROC
    mov r10, rcx                            ; syscall ABI: arg1 -> r10
    xor r11d, r11d
    or r11d, r11d
    mov eax, DWORD PTR [SC_SsnTable + 248]  ; load encrypted SSN
    xor eax, SC_XOR_KEY                           ; decrypt
    jmp QWORD PTR [SC_SyscallAddrTable + 496]     ; -> ntdll gadget
SC_NtReadVirtualMemory ENDP


; --- SC_NtTerminateThread (indirect: jmp to syscall;ret in ntdll) ---
SC_NtTerminateThread PROC
    mov r10, rcx                            ; syscall ABI: arg1 -> r10
    push 050h
    pop r11
    fnop
    mov eax, DWORD PTR [SC_SsnTable + 252]  ; load encrypted SSN
    xor eax, SC_XOR_KEY                           ; decrypt
    jmp QWORD PTR [SC_SyscallAddrTable + 504]     ; -> ntdll gadget
SC_NtTerminateThread ENDP


; --- SC_NtResumeProcess (indirect: jmp to syscall;ret in ntdll) ---
SC_NtResumeProcess PROC
    mov r10, rcx                            ; syscall ABI: arg1 -> r10
    mov r11d, 017h
    lea r11, [r11]
    nop DWORD PTR [rax + 00h]
    mov eax, DWORD PTR [SC_SsnTable + 256]  ; load encrypted SSN
    xor eax, SC_XOR_KEY                           ; decrypt
    jmp QWORD PTR [SC_SyscallAddrTable + 512]     ; -> ntdll gadget
SC_NtResumeProcess ENDP


; --- SC_NtResetEvent (indirect: jmp to syscall;ret in ntdll) ---
SC_NtResetEvent PROC
    mov r10, rcx                            ; syscall ABI: arg1 -> r10
    cmp r11d, 058h
    nop
    lea rsp, [rsp + 00h]
    fnop
    mov eax, DWORD PTR [SC_SsnTable + 260]  ; load encrypted SSN
    xor eax, SC_XOR_KEY                           ; decrypt
    jmp QWORD PTR [SC_SyscallAddrTable + 520]     ; -> ntdll gadget
SC_NtResetEvent ENDP


; --- SC_NtResumeThread (indirect: jmp to syscall;ret in ntdll) ---
SC_NtResumeThread PROC
    mov r10, rcx                            ; syscall ABI: arg1 -> r10
    xchg r11, r11
    test r11d, 0F5h
    nop DWORD PTR [rax + 00h]
    nop
    mov eax, DWORD PTR [SC_SsnTable + 264]  ; load encrypted SSN
    xor eax, SC_XOR_KEY                           ; decrypt
    jmp QWORD PTR [SC_SyscallAddrTable + 528]     ; -> ntdll gadget
SC_NtResumeThread ENDP


; --- SC_NtSetInformationProcess (indirect: jmp to syscall;ret in ntdll) ---
SC_NtSetInformationProcess PROC
    mov r10, rcx                            ; syscall ABI: arg1 -> r10
    xchg r11, r11
    xchg r11, r11
    mov eax, DWORD PTR [SC_SsnTable + 268]  ; load encrypted SSN
    xor eax, SC_XOR_KEY                           ; decrypt
    jmp QWORD PTR [SC_SyscallAddrTable + 536]     ; -> ntdll gadget
SC_NtSetInformationProcess ENDP


END
